---
- name: setup group
  group: name="{{ grafana_group }}" system=yes
  tags:
    - grafana

- name: setup user
  user: name="{{ grafana_user }}" system=yes group="{{ grafana_group }}"
  tags:
    - grafana

- name: create grafana dirs
  file:
    path="{{ item|safe|trim }}"
    state=directory
    owner="{{ grafana_user }}"
    group="{{ grafana_group }}"
    mode=777
    recurse=yes
  changed_when: false
  with_items:
    - "{{ grafana_opt_dir }}"
    - "{{ grafana_log_dir }}"
    - "{{ grafana_config_dir }}"
  tags:
    - grafana


