---
- name: copy grafana docker-compose file
  template:
     dest="{{ grafana_opt_dir }}/docker-compose.yml"
     owner="{{ grafana_user }}"
     group="{{ grafana_group }}"
     mode=777
     src=docker-compose.yml
  tags:
    - grafana
