version: '3.1'
services:
  grafana_service:
    image: anmolnagpal/grafana:{{ grafana_version }}
    container_name: grafana
    ## settings_template_start ##
    privileged: true
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 165536
        hard: 165536
    cap_add:
      - ALL
    ## settings_template_end ##
    volumes:
      - {{ grafana_log_dir }}:/var/log/grafana
      - {{ grafana_config_dir }}/grafana.yml:/usr/share/grafana/config/grafana.yml
    ports:
      - {{ grafana_port }}:{{ grafana_port }}
    network_mode: host

